image: gitlab.labranet.jamk.fi:4567/kivive/gitlab-plantuml-docker

pages:
    script:
        - pip install mkdocs
        - pip install mkdocs-material
        - mkdocs --version
        - mkdocs build
    artifacts:
        paths:
            - public
    tags:
        - general
