site_name: OPF Projektirunko kursseille TTOS0800+TTOS0900 
site_url: http://open-project-framework.pages.labranet.jamk.fi/opf-for-ttos0800-ttos0900-v1
site_author: Team X 
docs_dir: dokumentit
site_dir: public
site_name: Example site

markdown_extensions:
  - plantuml-markdown
  - toc:
      anchorlink: True
      separator: "_"
  - admonition
  - tables
  - sane_lists

theme:
  name: 'material'
  palette:
    primary: 'black'
    accent: 'black'
  logo:
    icon: 'assignment'
